
version: '3'

services:
  server:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8022:8000"
    external_links:
     - uma-db:db
