version: '3.4'

services:
  naxamap:
    container_name: uma-db
    image: mdillon/postgis:11-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: postgres-data
