# Generated by Django 2.2.10 on 2020-04-12 17:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20200412_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipolygon', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326)),
                ('Point', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Linestring', django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326)),
                ('Multistring', django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4326)),
                ('Multipoint', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
    ]
